### ISSUE TITLE
Error while accessing parts library in 3DFindIt

### ISSUE THREAD

**Issue by Footz355** [cadenasgmbh/3dfindit-freecad-integration#14]
Greetings, while trying to load a part from the3DFindIt part browser within FreeCAD an error occurs with following details:

```
Error: Error creating WebGL context.
    at https://www.3dfindit.com/en-GB/webcomponents.js:1993:5281
    at i (https://www.3dfindit.com/en-GB/webcomponents.js:9:247)
    at withTranslation(Component)
    at div
    at div
    at t.Tabs (https://www.3dfindit.com/en-GB/webcomponents.js:1221:1248)
    at div
    at t.Viewer (https://www.3dfindit.com/en-GB/script.js:1:836320)
    at div
    at div
    at t (https://www.3dfindit.com/en-GB/script.js:1:23466)
    at t.DigitalTwin (https://www.3dfindit.com/en-GB/script.js:1:801355)
    at t (https://www.3dfindit.com/en-GB/thirdparty.js:1:705767)
    at t (https://www.3dfindit.com/en-GB/thirdparty.js:1:707915)
    at div
    at t (https://www.3dfindit.com/en-GB/script.js:1:23466)
    at t.CADBridgeHOC (https://www.3dfindit.com/en-GB/script.js:1:552871)
    at t.CadJobsContextManager (https://www.3dfindit.com/en-GB/script.js:1:686264)
    at t.NotificationsContextManager (https://www.3dfindit.com/en-GB/script.js:1:703429)
    at t.LocationListener (https://www.3dfindit.com/en-GB/script.js:1:680902)
    at t.PartComparisonContextManager (https://www.3dfindit.com/en-GB/script.js:1:171949)
    at t.GlobalSearchContextManager (https://www.3dfindit.com/en-GB/script.js:1:695767)
    at t.SearchContextManager (https://www.3dfindit.com/en-GB/script.js:1:707603)
    at t.SearchTagContextManager (https://www.3dfindit.com/en-GB/script.js:1:713600)
    at t (https://www.3dfindit.com/en-GB/thirdparty.js:1:703116)
    at t (https://www.3dfindit.com/en-GB/thirdparty.js:1:690040)
    at N (https://www.3dfindit.com/en-GB/thirdparty.js:1:742688)
    at t (https://www.3dfindit.com/en-GB/script.js:1:23466)
    at t.Main (https://www.3dfindit.com/en-GB/script.js:1:129421)

```
While using a standalone website it worked ok.
I am using FreeCAD Link Stage 3

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.1021.26244 +5249 (Git)
Build type: Release
Branch: LinkDaily
Hash: d307b5c936403e8dca3f24b5c1e64bd16c88b28d
Python version: 3.8.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.2

**Comment by Footz355** [comment]
Just doublechecked it with FreeCAD 0.21 developments Master branch. Works fine. I guess I have to wait for realthunder to merge his branch with upstream before I report an issue with his branch.
